spring.application.name=backend

# Spring Security Default User
#spring.security.user.name=admin
#spring.security.user.password=admin123

# MySQL Database (Production) - Kullanmak icin H2 satirlarini yorum yapin
#spring.datasource.url=jdbc:mysql://localhost:3306/utms?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Istanbul
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# JPA/Hibernate Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true


# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

#Önemli Not: Spring Boot 3+ sürümlerinde, Hibernate tablolar? olu?turmadan
# önce data.sql çal??maya çal??abilir ve "Table not found" hatas? alabilirsin.
#Bunu engellemek için application.properties dosyana ?u sat?r? eklemelisin:
spring.jpa.defer-datasource-initialization=true


# H2 Database (Development)
#spring.datasource.url=jdbc:h2:file:./data/utms-db;AUTO_SERVER=TRUE
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.h2.Driver


#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

spring.sql.init.mode=always


#http://localhost:8080/h2-console
#JDBC URL --> jdbc:h2:file:./data/utms-db




spring.datasource.url=jdbc:h2:mem:utms-db;DB_CLOSE_DELAY=-1;MODE=MySQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


# Spring Mail Yap?land?rmas? (Gmail Örne?i)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nadegati@gmail.com
spring.mail.password=uygulama-ozel-sifreniz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

